### ISSUE TITLE
Empty Email

### ISSUE THREAD

**Issue by valireality** [begleysm/ipwatch#1]
received emails with changed ip are empty, there is no new ip.

**Comment by begleysm** [comment]
I just set everything up on a fresh virtual machine, using gmail as the sending service, and was successful in receiving a populated email from the system.

I went ahead and fleshed out the installation guide in [README.md](https://github.com/begleysm/ipwatch/blob/master/README.md) a bit more.  Try following it and see if it resolves your issue.
