### ISSUE TITLE
Do not updating oldip.txt before successfully sending email

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#10]
hello,

The new ip should not be written into the txt file before program ensure email is successfully sending out.

Sometimes the program did not send email successfully for whatever reason. 

```
# python3 /opt/ipwatch/ipwatch.py /opt/ipwatch/config.txt
GetIP: Try 1: Good IP: xxx.xxx.xxx.xxx
Current IP differs from old IP.
ERROR: unable to send email
#
#
# python3 /opt/ipwatch/ipwatch.py /opt/ipwatch/config.txt
GetIP: Try 1: Good IP: xxx.xxx.xxx.xxx
Current IP = Old IP.  No need to send email.
```

Then the program will not send the email again on next iteration since it did not know , the last sending did not succeed, it assume that the the ip in oldip.txt is already sent out, So this time "No need to send email" again.

**Comment by begleysm** [comment]
This is a good suggestion.  Thanks.  I don't have time this second to work that update but I'll leave this issue open until I do.

**Comment by begleysm** [comment]
This update has been implemented.  Now oldip.txt will only be updated after an email has successfully been sent.  See commit https://github.com/begleysm/ipwatch/commit/06cbcc857bbb0d09a8c244e1b656ce9958dcc17b
