### ISSUE TITLE
do "ehlo" after "login"

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#11]
Is it ok to set value of machine in config.txt when sending mail ?

```
smtpObj.ehlo(name=machine)
```

I'd like to identify client in email header, but when I added the above line, I found it did not work. 

When I put it after login, it works as expected: the email header contain the string of machine ID.

I am using Python 3.6.8 in centos 7

https://github.com/begleysm/ipwatch/blob/42ae4323f8208b66ce2d2b2bd1305fd67d76d5da/ipwatch.py#L237

**Comment by begleysm** [comment]
I'm actually not all that smart on sending emails with sendmail.  I largely copied/pasted from an example for this portion of the code.

It sounds like you got a configuration that works.  I believe you're saying you changed `smtpObj.ehlo()` to `smtpObj.ehlo(name=machine)` and the moved it to occur after `smtpObj.login(username, password)`?

If not can you post a code snippet of your change or initiate a pull request?

I have been accomplishing the "machine ID" by changing the subject line to include the machine name.

**Comment by begleysm** [comment]
I've implemented your suggestions. See commit https://github.com/begleysm/ipwatch/commit/0b6ce4ae2e79f7567736266503ddf264b25bd859
