### ISSUE TITLE
use a module to form the email message

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#14]
I saw an answer from StackOverflow related to how to send email programmically. 
[Python Smptlib Email (Wrong subject & message field)](https://stackoverflow.com/a/38544003)

I wonder If it's possible/necessary to use a module to form the email message. 

- make the ipwatch more robust ?
- the module can work both in most common env, i.e., work with both python2/3 ?

**Comment by begleysm** [comment]
The suggested way of sending email in the link is already how ipwatch works.  The only significant difference is that the linked example use the MIMEText format for the message body, but I don't think this would have much of an impact with such a simple message body.
