### ISSUE TITLE
show exception to end-user when sending the email 

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#15]
I recently met an issue during sending email. 

I get the error message "unable to send email ...", but it's useful to show the detail exception information to end-user to do the trouble-shooting. Since end-user is repsonsible to fill the config.txt, show the error message on the console is helpful to figure out what's going wrong. especially auth error.

When I remove the try except, I get the internal error msg so I am able to do more investigation.
```
Current IP differs from old IP.
Traceback (most recent call last):
  File "/opt/ipwatch/ipwatch.py", line 321, in <module>
    sm_ret = sendmail(oldip,  currip,  server, config.sender, config.sender_email, config.receiver, config.receiver_email, config.sender_username, config.sender_password, config.subject_line,  config.machine,  config.smtp_addr)
  File "/opt/ipwatch/ipwatch.py", line 254, in sendmail
    smtpObj.sendmail(sender_email, receiver_emails[i], messages[i])
  File "/usr/lib64/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'2f1360f5227ac95-29a5c Mail rejected')
```

**Comment by wushuzh** [comment]
Anyone meet the similar error msg ? 

I did some googling, it seem the smtp server is rejecting since the email looks like a spam ?

**Comment by begleysm** [comment]
I've updated the code to print out the Exception when it fails to send an email (see https://github.com/begleysm/ipwatch/commit/1b7f49dc4b9a778ccb1bd4d0e9058f35117e2f44).

**Comment by begleysm** [comment]
I have not received a 550 error, but I've only tested the software by sending both from Gmail, to Gmail.

I quick Google search suggests you're likely right, that the email server is considering your message spam.

This page (https://www.enginemailer.com/blog/email-error-550-what-is-it-and-how-to-fix-it) lists a few reasons why this might happen
1. Your email address has been compromised and so is blocked by the recipient's mail server.
2. The recipient's email address doesn't exist.
3. The recipient's email address is temporarily unavailable or suspended.
4. The recipient's hosting server is temporarily unavailable.
5. Your domain name is invalid or blocked.
6. Your internet gateway has a firewall or a filtering feature which mistakenly identified your email as spam and blocked it.
7. Your email is mistakenly identified as spam by the recipient's mail server.
8. You are using your email client from a different IP address.
9. The recipient's mail server failed to identify your email address.
and most of them are that someone in the chain thinks you're message is spam.

If you're using Gmail, have you enabled **Less Secure Access** and answered the **Critical Security Alert** as per here https://github.com/begleysm/ipwatch#gmail?

If you're using another email server, you may to see if you can whitelist your sending address/ip.

Lastly you may want to try another sending email service (at least to debug).  As implied, I've had success with Gmail (by following these instructions https://github.com/begleysm/ipwatch#gmail).

**Comment by wushuzh** [comment]
Thanks a lot, I will do more investigation with my own email service.

I've seen the exception printing code is available. Now this issue can be closed.
