### ISSUE TITLE
gmail application password

### ISSUE THREAD

**Issue by pjuster** [begleysm/ipwatch#17]
I use 2FA on my google account so could not use the less secure option, after a quick google I found I could create an application password and use that in your script

https://support.google.com/accounts/answer/185833?p=InvalidSecondFactor&visit_id=637635832706184560-3332462906&rd=1

works flawlessly thanks

**Comment by begleysm** [comment]
This is great info!  Thanks for sharing!

I've added this info to the Gmail section of README.md here: https://github.com/begleysm/ipwatch/commit/4384adb18632b3e62ec71dcc38649cc4cd484e7e

Commit: https://github.com/begleysm/ipwatch/commit/4384adb18632b3e62ec71dcc38649cc4cd484e7e
