### ISSUE TITLE
send email to multi receivers in one shot

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#18]
Ask for feature to send IP to multi receivers in one email.

My scenario is one of the receiver  (for example, A@email.com ), will reponse to the email, notice the result to sender (for example, S@email.com) and other receiver (for example, B@email.com and C@email.com) , which is action result related to IP address ipwatch found ). 

If ipwatch can send one email to multi receivers (A/B/C@email.com), then all the receiver can be noticed. Otherwise, B/C@email.com cannot know the result.

In addition, sending email per receiver may easily exceed the daily limitation in some cases.

**Comment by begleysm** [comment]
I'll look into this when I find some time.

**Comment by shag00** [comment]
I send emails to multiple people if the IP address changes, this feature is already available.

**Comment by shag00** [comment]
This feature is already available.

**Comment by begleysm** [comment]
Good call @shag00 , yeah I added it but never closed this out.
