### ISSUE TITLE
Bad servers

### ISSUE THREAD

**Issue by Simbatastic** [begleysm/ipwatch#22]
servers.json need to be updated. due to at least one is bad but other than that, great tool.

**Comment by Bahama03** [comment]
Yep, site ipanywhere.com is no longer active and working so it should be deleted from the list.

**Comment by Gandalf-79** [comment]
Concur - ipanywhere.com domain is up for sale and not valid now.

> Yep, site ipanywhere.com is no longer active and working so it should be deleted from the list.

**Comment by Gandalf-79** [comment]
> Thanks for the feedback. Should be fixed now (in commit [3aa88c2](https://github.com/begleysm/ipwatch/commit/3aa88c27b4d533e51c03630c9f0f779ac382f020))

Thanks!!!!
