### ISSUE TITLE
Is it possible to set mail header Content-Transfer-Encoding

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#7]
Is it possbile to set the mail header "Content-Transfer-Encoding" ?

Or any workaround I can try to set this. My help desk said the mail cannot be parsed due to missing this header information.

**Comment by begleysm** [comment]
It looks like most servers/clients assume "default" values for `Content-Transfer-Encoding` (and several other email header components).  I added `Mime-Type`, `Content-Type`, & `Content-Transfer-Encoding` explicitly which you can see on Line 221 of _ipwatch.py_ [here](https://github.com/begleysm/ipwatch/blob/42ae4323f8208b66ce2d2b2bd1305fd67d76d5da/ipwatch.py#L221).

Reclone the project and let me know if it works.

**Comment by wushuzh** [comment]
The latest version works as expected. Thanks a lot.

Also if I want to send mail to multi receivers, I should list all of their email addresses in the `receiver_email` and delimited by ";" ?

Is it possible to add an example in readme or wiki.

**Comment by wushuzh** [comment]
I think I should create a separate issue for multi receivers. 

The content transfer encoding issue can be closed.
