### ISSUE TITLE
how to send email to multi users

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#8]
I want to send mail to multi receivers, How should I do ?

For example, listing all of their email addresses in the receiver_email and delimited by ";" ? 

If it's possible, it's better to add an example in readme or wiki.

**Comment by begleysm** [comment]
The software doesn't currently support this feature.  But [sendmail can do it](https://stackoverflow.com/questions/8856117/how-to-send-email-to-multiple-recipients-using-python-smtplib) does support multiple recipients.  I'll look into updating to fully support multiple email addresses although I don't have time today.

In the meantime you should be able to change line [216 ](https://github.com/begleysm/ipwatch/blob/42ae4323f8208b66ce2d2b2bd1305fd67d76d5da/ipwatch.py#L216) of [ipwatch.py](https://github.com/begleysm/ipwatch/blob/master/ipwatch.py) from `receivers = [receiver_email]` to something like `receivers = ['email1@gmail.com', 'email2@gmail.com']`

I'll leave this open until I can update the software to fully support multiple recipients from the config file.

**Comment by begleysm** [comment]
I've updated the software to support emailing multiple recipients.  Simply amend the "receiver" and "receiver_email" lines with additional, comma delimited, email addresses (see updated [README.md](https://github.com/begleysm/ipwatch/blob/master/README.md) for an example).

See commit https://github.com/begleysm/ipwatch/commit/65cda6df73ef3ab3da647b06204cc4e2e2bfd262
